### ISSUE TITLE
Equivalent Drop-In SMD Resistor Network

### ISSUE THREAD

**Issue by MrMojoRisinGottaKeepOnRisin** [dojoe/roland-mram-card#1]
I just built and tested three DOJOE Roland MRAM Cards using the new part from Panasonic (P/N: **EXB-E10C103J**) and all is well. The equivalent SMD Resistor Network you have listed in the BOM is indeed a valid drop-in replacement for the Bourns CAT25. Same footprint, specs and everything.

**Comment by dojoe** [comment]
Thanks a lot for reporting back! I updated the README.
